set(_CATKIN_CURRENT_PACKAGE "ap_navigation")
set(ap_navigation_VERSION "0.0.0")
set(ap_navigation_MAINTAINER "Randy Mackay <rmackay9@yahoo.com>")
set(ap_navigation_PACKAGE_FORMAT "2")
set(ap_navigation_BUILD_DEPENDS )
set(ap_navigation_BUILD_EXPORT_DEPENDS )
set(ap_navigation_BUILDTOOL_DEPENDS "catkin")
set(ap_navigation_BUILDTOOL_EXPORT_DEPENDS )
set(ap_navigation_EXEC_DEPENDS )
set(ap_navigation_RUN_DEPENDS )
set(ap_navigation_TEST_DEPENDS )
set(ap_navigation_DOC_DEPENDS )
set(ap_navigation_URL_WEBSITE "")
set(ap_navigation_URL_BUGTRACKER "")
set(ap_navigation_URL_REPOSITORY "")
set(ap_navigation_DEPRECATED "")